### ISSUE TITLE
Turkcell Cüzdan ile ödeme geliştirmesi

### ISSUE THREAD

**Issue by ibrahimgunduz34** [paranoiaproject/paranoia#16]
Turkcell Cuzdan, turkcell tarafından geliştirilen asenkron bir ödeme yöntemidir. Ödeme isteği gönderildikten sonra kullanıcının aksiyon gerçekleştirip ödemenin tamamlanması durumu ayrı bir istekle dinlenir. 

Konuyla ilgili geliştirmenin gerçekleştirilmesi.

**Comment by nurettintopal** [comment]
Turkcell bu hizmetini kapatacağını açıkladı. O yüzden buna gerek kalmadı sanırım. 

“Turkcell Cuzdan, 31 Ocak 2015 tarihi itibariyle bankalarla anlaşmalarımızın sona ermesi nedeniyle kullanımdan kaldırılacaktır. GarantiParam ve CepteParacard bakiyelerinizi harcamanız veya çekmeniz önemle rica olunur”

http://eticaretmag.com/turkcell-mobil-cuzdandan-vazgecti/

**Comment by ibrahimgunduz34** [comment]
Teşekkürler.
