### ISSUE TITLE
Oneriler

### ISSUE THREAD

**Issue by o** [paranoiaproject/paranoia#44]
Dayi selam,

Onerilerimi topluca yazmak istedim.

* Composer entegrasyonu
* Zend_Loader'in kaldirilmasi (Composer Symfony2 Classloader kullandigindan buna gerek yok)
* Pext (?)'in composer kullanimina binaen ayri repoya alinmasi ya da JMS\Serializer ile replace edilmesi
* EventManager'in cok daha guclu bir EventManager ile degistirilmesi (e.g Symfony2 EventDispatcher)
* PSR2 Standartlarina uygunluk
* Communication yapisinda yer alan HTTP adapter'in Amazon PHP SDK'sininda kullandigi Guzzle ile degistirilmesi
* Event dispatcher vasitasiyla Logger entegrasyonu (Guzzle da da logger mevcut, buna gerek kalmayabilir)(Monolog PSR-3 Logger)
* SOAP icin Zend\Soap entegrasyonu

**Comment by GoktugOzturk** [comment]
İbrahim bu issue çözülmüş gibi sanki

**Comment by ibrahimgunduz34** [comment]
Aynen :)  Birtek sanırım şu diziden xml generate eden kütüphanenin JMS Serializer ile replace edilmesi konusu var.JMS Serializer ı paranoia2 de entegre etmiştim. (benim forkdaki development dalında) Ancak hem geliştirme/zaman hem de çalışma mailyeti olarak baktığında bence zaman harcamayı pek haketmiyor. Sanırım annotation kullanımından dolayı bazı doctrine bağımlılıkları filan var. Bence deymez. Eğer gelecekte çok kompleks bir xml generate etmek gerektiğinde mevcut serializer işimizi görmezse o zaman bakalım derim.
