### ISSUE TITLE
Iyzico Entegrasyonu

### ISSUE THREAD

**Issue by uguratar** [paranoiaproject/paranoia#72]
Iyzico popüler olmaya başladı, yatırım da aldılar bildiğim kadarıyla. Entegre edilmesi düşünülebilir.

Oldukça basit html form örneğini burada paylaşmışlar fakat direkt API entegrasyonu da var. Dökümanlar mevcut gerektiği takdirde sağlayabilirim.
https://www.iyzico.com/entegrasyondirectentegrasyon

**Comment by ibrahimgunduz34** [comment]
Gayet basitmiş gerçekten. Ellerinden öper uğur uygun olduğunda o zaman :)

**Comment by uguratar** [comment]
Hayirlisi Ibrahim :) python surumu bitsin php versiyonunu yazmaktan mutluluk duyarim.

**Comment by ibrahimgunduz34** [comment]
Büyüksün dostum. Kolay gelsin. Selamlar, sevgiler.
