### ISSUE TITLE
Taksitlendirme hk

### ISSUE THREAD

**Issue by navinova** [paranoiaproject/paranoia#80]
Merhaba,

Öncelikle frameworkünüz ve emeğiniz için çok teşekkürler.

Taksitlendirme işlemini yapabileceğimiz bir örnek kod verme şansınız var mı acaba?

Kolay gelsin

**Comment by ibrahimgunduz34** [comment]
Merhaba,
Taksitlendirme işlemi için request nesnesinin setInstallment() metodunu kullanabilirsiniz.

$request->setInstallment(2);
