### ISSUE TITLE
Config Dosyası

### ISSUE THREAD

**Issue by LadyArch3r** [paranoiaproject/paranoia#82]
Bankaların pos bilgilerinin girilebileceği bir config dosyası mevcut mu ?

**Comment by ibrahimgunduz34** [comment]
Hayır. Kütüphanenin herhangi bir konfigürasyon tipi ile ilgili bir bağımlılığı bulunmuyor. Dilediğiniz konfigürasyon aracından aldığınız bilgileri kütüphanedeki uygun konfigürasyon sınıflarına aktararak paranoia'ya konfigürasyon verisi iletebilirsiniz.
