### ISSUE TITLE
Nestpay entegrasyonunda Communication Error hatası

### ISSUE THREAD

**Issue by navinova** [paranoiaproject/paranoia#84]
Merhaba,

Ziraat bankasının bize verdiği kullanıcı id, kullanıcı adı ve şifre ile sisteme bağlanmaya çalıştığımda communication error alıyorum. Bir öneriniz var mı acaba?

**Comment by ibrahimgunduz34** [comment]
CommunicationError hatası genellikle curl un genellikle uzak sunucuya erişememesi durumunda fırlatılıyor. Uzak sunucu adresi veya sunucunuzun ilgili adrese erişimi ile ilgili bir sorun olabilir.

**Comment by navinova** [comment]
Teşekkürler. sanırım url i setlememiz gerekiyor.
