### ISSUE TITLE
Abstract adaptor sinifindaki formatlama fonksiyonlarinin disari alinmasi

### ISSUE THREAD

**Issue by ibrahimgunduz34** [paranoiaproject/paranoia#94]
Veri formatlama AbstractAdapter sinifinin sorumlulugunda degildir. Formatlama fonksiyonlari Formatter namespace i altinda yeni bir sinif ailesine tasinmalidir.

**Comment by GoktugOzturk** [comment]
her adapter için bir tane de formatter mı yapmayı planlıyorsun? Yoksa ilgili veri üzerinde ihtiyaç duyulan tüm formatlamaları yapabilen bir sınıf mı olacak ?

**Comment by ibrahimgunduz34** [comment]
@GoktugOzturk Aslinda kodun icinde yaptigimiz birkac tane temel formatlama islemi var. Verilen currency kodunu sayisal veya alfanumeric iso kur koduna donusturmek, decimal sayiyi money type dedikleri integer sayiya donusturmek gibi. Isin amaci, AbstractAdapter sinifindaki formatAmount, formatCurrencyCode gibi aslinda adaptor implementasyonu ile ilgili olmayan metodlarin isini Formatter namespace i altinda yeralan, ayni metod imzasina sahip siniflara devretmek.

**Comment by GoktugOzturk** [comment]
@ibrahimgunduz34 
iyi de her adaptör çekilecek tutarı veya kur değerini farklı isteyebiliyor. 
birisi 34.45 alıyor. öbürü 34,45 diğeri 3445 
Kurda da aynı şey, çoğu TL için evrensel para kodu olan 949 alsa da, iyzipay: TRY, paynet YTL, posnet YT gibi saçma değerler alabiliyor.
aynı şey taksitlerde de geçerli; 
birisi çift hane taksit sayısı istiyor, diğeri sıfır yerine boş gönderin diyor, başka biri tek çekim ise 0 gönder diyor...

Sonuç olarak adaptör bazında değişebilen formatlama ihtiyaçları var.

**Comment by ibrahimgunduz34** [comment]
Aslinda para biriminin veya gonderilecek olan tutarin provider a gore formatlanmasi o provider in ic surecleri. Dedigin gibi Garanti ve Nestpay numeric iso kur kodlarini kullanirken Posnet muhtemelen kendilerinin belirledikleri Yt, Eu gibi iki harfli kur kodlari kullaniyorlar.  
Fakat is implementasyona gelince buradaki amac, kutuphaneyi her isi yapan buyuk siniflardan kurtarip, daha az sorumluluga sahip, sadece kendi isini yapan, test edilebilir kucuk parcalar haline getirmek. 

Ornegin X provideri icin kullanicinin girdigi currency kodunun, numeric iso currency koduna cevrilmesi bekleniyorsa, bu is bundan sorumlu olan sinif tarafindan icra edilmeli gibi.

Aslinda gunun sonunda dusundugum sey, provider siniflarinin, kendisiyle ilgili bilesenleri bilen transaction objeleriyle konusan, isin detayindan cok da haberdar olmayan facade siniflari haline getirmek.

Ne dersin ?
